---
collections:
  - name: community.windows
  - name: community.general
  - name: community.dns
  - name: community.crypto
  - name: community.kubernetes
  - name: community.kubevirt
  - name: community.libvirt
  - name: community.postgresql
  - name: community.vmware
  - name: awx.awx
