---
collections:
  - name: community.windows
  - name: community.general
    version: <5.0.0
  - name: community.dns
  - name: community.crypto
  - name: community.kubernetes
  - name: community.kubevirt
  - name: community.libvirt
  - name: community.postgresql
  - name: community.vmware
